version: "3.1"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - api-gateway/.env
    ports:
      - ${API_PORT:-8080:8080}
    networks:
      net1:
        ipv4_address: 172.222.0.2

  web:
    image: node:20.19-slim
    restart: unless-stopped
    working_dir: /app
    entrypoint: "/usr/bin/bash"
    volumes:
      - ./web/:/app/
    command: -c "npm install && npm run build-watch"
    networks:
      net1:
        ipv4_address: 172.222.0.42

  nginx:
    image: nginx:1.29.0
    restart: unless-stopped
    volumes:
      - ./web/dist/:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT:-4200}:80
    networks:
      net1:
        ipv4_address: 172.222.0.80

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - scheduler/.env
    networks:
      net1:
        ipv4_address: 172.222.0.4

  thoi-khoa-bieu-parser: # OPTIONAL
    build:
      context: ./thoi-khoa-bieu-parser
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    networks:
      net1:
        ipv4_address: 172.222.0.5

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - worker/.env
    command: ["node", "./dist/launch-worker-rabbitmq-v1.js"]
    networks:
      net1:
        ipv4_address: 172.222.0.6

  mongo:
    image: mongo:4.2
    command:
      - --config
      - /etc/mongod.conf
    env_file:
      - mongodb/.env
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    restart: unless-stopped
    networks:
      net1:
        ipv4_address: 172.222.0.7

  rabbitmq:
    image: rabbitmq:3.12-management
    env_file:
      - rabbitmq/.env
    restart: unless-stopped
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/data/mnesia:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672
    networks:
      net1:
        ipv4_address: 172.222.0.8

networks:
  net1:
    ipam:
      config:
        - subnet: 172.222.0.0/24
